#!/bin/bash
# dtree
rm -f out.*
rm -f *.json
set -e
export SHELLOPTS
cd "$2"

PBPWD="$(pwd)"
fname="$1"
here="$2"
caller="$3"
./REFRESH-BOOTSTRAP

# push a new value of PBPWD onto the stack, which will get unwound to its previous value when this script ends
PBPWD="$(pwd)"

# convert dtree tool diagram to JSON
${PBP}/das2json dtree-transmogrifier.drawio

# run the tool on the given filename
python main.py "${PBPCALLER}/${fname}.drawio" main dtree-transmogrifier.drawio.json | ${PBP}/splitoutputs

## move results to caller's working directory, if no errors
if [ -f out.✗ ]
then
    echo
    echo ">> ERROR <<"
    cat out.✗
else
    mv out.frish "${PBPCALLER}/${fname}.frish"
    mv out.dt "${PBPCALLER}/${fname}.dt"
    mv out.py "${PBPCALLER}/${fname}.py"
    mv out.js "${PBPCALLER}/${fname}.js"
fi

