#!/bin/bash
rm -f out.*
rm -f *.json
set -e
export SHELLOPTS
fname="$1"

echo
echo '*****'
for i in PBP PBPHERE PBPCALLER PYTHONPATH fname
do
    echo "$i = ${!i}"
done
echo '*****'
echo

${PBP}/das2json dtree-transmogrifier.drawio
python main.py "${PBPCALLER}/${fname}.drawio" main dtree-transmogrifier.drawio.json | ${PBP}/splitoutputs
if [ -f out.✗ ]
then
    cat out.✗
else
    mv out.frish "${PBPHERE}/${fname}.frish"
    mv out.dt "${PBPHERE}/${fname}.dt"
    mv out.py "${PBPHERE}/${fname}.py"
    mv out.js "${PBPHERE}/${fname}.js"
fi

